# Generated by Django 3.2.5 on 2021-07-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='author_name',
            new_name='author',
        ),
    ]
